/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MfProductCart {}
  interface MfProductView {}
}

declare global {


  interface HTMLMfProductCartElement extends Components.MfProductCart, HTMLStencilElement {}
  var HTMLMfProductCartElement: {
    prototype: HTMLMfProductCartElement;
    new (): HTMLMfProductCartElement;
  };

  interface HTMLMfProductViewElement extends Components.MfProductView, HTMLStencilElement {}
  var HTMLMfProductViewElement: {
    prototype: HTMLMfProductViewElement;
    new (): HTMLMfProductViewElement;
  };
  interface HTMLElementTagNameMap {
    'mf-product-cart': HTMLMfProductCartElement;
    'mf-product-view': HTMLMfProductViewElement;
  }
}

declare namespace LocalJSX {
  interface MfProductCart extends JSXBase.HTMLAttributes<HTMLMfProductCartElement> {
    /**
    * Define a pQutUpdated Event
    */
    'onPQutUpdated'?: (event: CustomEvent<any>) => void;
  }
  interface MfProductView extends JSXBase.HTMLAttributes<HTMLMfProductViewElement> {
    /**
    * Define a productAdded Event
    */
    'onProductAdded'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'mf-product-cart': MfProductCart;
    'mf-product-view': MfProductView;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


